resource_group_name = "my-apim-resource-group"
location            = "eastus"
apim_service_name   = "my-apim-service"
publisher_name      = "My Company"
publisher_email     = "info@mycompany.com"
sku_name            = "Developer_1"